carts/urls.py

from django.urls import path

from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view,
)
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home, name='checkout'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('update/', cart_update, name='update'),
]


ecommerce/urls.py
from . import views
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import RegisterView, LoginView, guest_register_view
from django.views.generic import TemplateView
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from billing.views import payment_method_view, payment_method_createview
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name="home"),
    path('about/', views.about_page, name="about"),
    path('contact/', views.contact_page, name="contact"),
    path('login/', LoginView.as_view(), name="login"),
    path('checkout/address/create/', checkout_address_create_view, name="checkout_address_create"),
    path('checkout/address/reuse/', checkout_address_reuse_view, name="checkout_address_reuse"),
    path('register/login/', guest_register_view, name="guest_register"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('api/cart/', cart_detail_api_view, name="api-cart"),
    path('cart/', include('carts.urls', namespace='cart')),
    path('billing/payment-method/', payment_method_view, name="billing-payment-method"),
    path('billing/payment-method/create/', payment_method_createview, name="billing-payment-method-endpoint"),
    path('register/', RegisterView.as_view(), name="register"),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include('products.urls', namespace='products')),
    path('search/', include('search.urls', namespace='search')),


]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py

from django.urls import path

from .views import (
    ProductListView,
    ProductDetailSlugView,
)
app_name = 'products'
urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),
]


templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css"
      integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>

<!--Stripe JS-->
<script src="https://js.stripe.com/v3/"></script>
<!--jquery-confirm JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>
<!--Django Secure AJAX JS-->
<script src="{% static 'js/csrf.ajax.js' %}"></script>
<!--eCommerce Custom JS-->
<script src="{% static 'js/ecommerce.js' %}"></script>
<!--eCommerce Main JS-->
<script src="{% static 'js/ecommerce.main.js' %}"></script>
<!-- js Render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.1/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
<script id="stripeTemplate" type="text/x-jsrender">

    <form class="payment-form" id="payment-form" data-token="{{:publishKey}}" data-next-url="{{:nextUrl}}">
  <div class="form-row">
    <!--<label for="card-element">-->
      <!--Credit or debit card-->
    <!--</label>-->
    <div id="card-element" class="form-control">
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display form errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class="btn btn-primary my-3 btn-load">{{:btnTitle}}</button>
</form>

</script>
{% endverbatim %}

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container">
    <a class="navbar-brand my-auto" href="{{ home_url }}">
        <i class="far fa-circle"></i>{% if brand_name %} {{ brand_name }} {% else %} CFE eCommerce {% endif %} </span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                <a class="nav-link" href="{{ contact_url }}">Contact</a>
            </li>
            <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                <a class="nav-link" href="{{ product_list_url }}">Products</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
                <a class="nav-link" href="{{ logout_url }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                <a class="nav-link" href="{{ login_url }}">Login</a>
            </li>
            <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                <a class="nav-link" href="{{ register_url }}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                <a class="nav-link" href="{{ cart_url }}"><span class="navbar-cart-count"> {{ request.session.cart_items }}</span>  <i class="fas fa-shopping-cart"></i></a>
            </li>
            <!--<li class="nav-item dropdown">-->
                <!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"-->
                   <!--data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
                    <!--Dropdown-->
                <!--</a>-->
                <!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
                    <!--<a class="dropdown-item" href="#">Action</a>-->
                    <!--<a class="dropdown-item" href="#">Another action</a>-->
                    <!--<div class="dropdown-divider"></div>-->
                    <!--<a class="dropdown-item" href="#">Something else here</a>-->
                <!--</div>-->
            <!--</li>-->

        </ul>
        {% include 'search/snippets/search-form.html' %}
    </div>
    </div>

</nav>